# Generated by Django 3.0.9 on 2020-08-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.TextField(blank=True, null=True)),
                ('pays', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('secteur', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entreprise',
                'managed': False,
            },
        ),
    ]
